### ISSUE TITLE
Thirst debuff not resetting properly.

### ISSUE THREAD

**Issue by skybix** [Charles445/SimpleDifficulty#16]
When have the thirst debuff and you drink from a source which would give you the debuff you keep the original cool down instead of resetting it to 30sec. This allow you to largely negate the challenge by waiting until the last second and the quickly filling you bar before the debuff runs out but not early enough for it to tick.

**Comment by Charles445** [comment]
I was unable to reproduce this, on my end it would replace the cooldown regularly.
There's a random chance that it doesn't replace the cooldown - make sure you're not simply running into that
