### ISSUE TITLE
[Suggestion] - Starting Saturation

### ISSUE THREAD

**Issue by 3D1ofakind** [Charles445/SimpleDifficulty#21]
In vanilla minecraft you start with a saturation of 5 upon creating a world, or simply dying. Therefore thirst saturation should also have a starting value of 5.

**Comment by Charles445** [comment]
Pretty good idea, I received your PM about this earlier but have been a bit busy lately. I'll have to look into it when I get the chance

**Comment by Charles445** [comment]
Added in 0.3.8
