### ISSUE TITLE
Drinking from rain does not work on the server

### ISSUE THREAD

**Issue by juraj-hrivnak** [Charles445/SimpleDifficulty#29]

**Comment by Charles445** [comment]
Sorry for taking over a year to get back to you on this stuff, RLTweaker's been keeping me busy

Have you checked to make sure the config for drinking rain is enabled on the server? Just in case it got turned off.

Some mods like SereneSeasons and Optifine make it so rain displays in strange ways, so drinking from this 'fake' rain isn't going to work. Try going to a Plains biome or something and see if it starts working there

**Comment by juraj-hrivnak** [comment]
Yes, also sorry for the late response. 

After some more testing, it seems to work as intended.
Sometimes other mods cause that mentioned 'fake' rain, but that's not an issue from this mod. (Weather2, SereneSeasons, Dynamic Surroundings )
