### ISSUE TITLE
Canteen Refilling

### ISSUE THREAD

**Issue by WiseHorror** [Charles445/SimpleDifficulty#3]
In Tough As Nails you could refill the canteen at a cauldron, but with this mod you can't.

In another note, if possible, config options for the canteen refill range, capacity and one-click refill as opposed to 3 clicks would be appreciated as well.

**Comment by Charles445** [comment]
Canteens will be refillable with cauldrons in 0.3.0, you can also drink from them
Haven't done the config for instant refill though, will leave this open as I think about it

**Comment by Charles445** [comment]
Instant refill has finally been added in 0.3.7, better late than never!
