### ISSUE TITLE
[Crash] LibVulpes, SimpleDifficulty, ChickenLib

### ISSUE THREAD

**Issue by SilverBackSpartan** [Charles445/SimpleDifficulty#30]
Crash happened while chilling on my spacestation and viewing my rocket's Gui

![image](https://user-images.githubusercontent.com/91655215/136925630-854b4f53-1cf5-4611-9265-f86c2e2dfff8.png)

https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2242

https://github.com/Advanced-Rocketry/AdvancedRocketry/files/7328395/crash-2021-10-12_04.51.04-client.txt

**Comment by Charles445** [comment]
Huh. so Advanced Rocketry has a fake world that says it's not remote even when it is.
I should be able to fix this on my end, but the mod isn't going to update for a while as there is much to do.

For now, make sure you do not put any thermometers into your rocket ship's storage.
If you already have a thermometer in your ship's storage and you need to remove it, go into your simpledifficulty config and change client > thermometer > enableThermometer    to false
That should disable the thermometer and allow you to move it out of storage.

**Comment by Charles445** [comment]
Fixed in 0.3.8
