### ISSUE TITLE
camera flipping with thirst edit

### ISSUE THREAD

**Issue by pkaifes** [Charles445/SimpleDifficulty#35]
Hello,
I am playing with this mod in 1.12.2 as it feels better than tough as nails, but similar. But there seems to be an effect where when the thirst meter goes down to 3.5, the camera flips upside down. Is there a way to stop this from happening?

**Comment by Charles445** [comment]
This sounds like a mod conflict, you could check if Enhanced Visuals is added and fiddle with the settings in that

**Comment by pkaifes** [comment]
That was it, Thank you for your help!
