### ISSUE TITLE
Can Chinese language be added to the mod？

### ISSUE THREAD

**Issue by WeiEAL** [Charles445/SimpleDifficulty#4]
Hello author
I have made Chinese language for your mod
File is here
[zh_cn.zip](https://github.com/Charles445/SimpleDifficulty/files/5093119/zh_cn.zip)
In addition, I want to repost your mod to the Chinese forum (mcbbs), the download link will point to curseforge, can I repost it?

(Sorry my English is not very good, use Google Translate)

**Comment by Charles445** [comment]
I had a friend who knows the language look over it.
The translation is great!
It has been added, thank you!
It's included in 0.3.1

You may repost the mod on mcbbs, that would be great
