### ISSUE TITLE
Compatibility for Armor Underwear

### ISSUE THREAD

**Issue by reddvilzz** [Charles445/SimpleDifficulty#43]
Hi there, 

Armor Underwear configuration is not showing with Simple Difficulty, and I mentioned with the dev at Armor Underwear [here](https://github.com/Wabbit0101/mods_hoardercraft/issues/145).

**Comment by MagmaSlime123** [comment]
Already exists.

**Comment by reddvilzz** [comment]
Oh right, sorry I don't know what I was thinking.
